### ISSUE TITLE
The relation between Observed Entity Role, ObjectOfInterest and Context Object

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [i-adopt/framework#1]
@mabablue @gwemon @SirkoS @huberrob 

I read the framework doc https://docs.google.com/document/d/1NGC5BQ9tKsGWnh_IFtMLBWu-BlT8vpulAanF6zYEr2I/edit#
the relations between Observed Entity Role, ObjectOfInterest and Context Object is ambiguous.
My suggestions are as follows:

OPTION 1
1. There is one concept called ObservedEntity, which can 'playrole' as ObjectOfInterest and Context Object
2. Property is a 'PropertyOf' **_ObservedEntity_** 
3. When an ObservedEntity assumes a role, it is 'constrainedBy'  Constraint.

OPTION 2
1. There is one concept called ObservedEntity, which can 'playrole' as ObjectOfInterest and Context Object
2. Property is a 'PropertyOf' **_ObjectOfInterest_** 
3. When an ObservedEntity assumes a role, it is 'constrainedBy'  Constraint.

any thoughts?

**Comment by SirkoS** [comment]
Can you maybe expand a little on the ambiguity you see in the structure, please?

From my current view, it's only a matter of getting the definitions right, but the structure overall seems fitting

**Comment by gwemon** [comment]
@kitchenprinzessin3880 please see @SirkoS 's question above. Is this still an open issue for you?

**Comment by kitchenprinzessin3880** [comment]
@SirkoS @gwemon 
The issue seems like has been addressed by @mabablue here (page 4), https://docs.google.com/document/d/1NGC5BQ9tKsGWnh_IFtMLBWu-BlT8vpulAanF6zYEr2I/edit#heading=h.3ja7jtv0ix8r.
